// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: black_list.proto

package black_list

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlackListCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployeeId string `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Reason     string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	AddedBy    string `protobuf:"bytes,3,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
}

func (x *BlackListCreate) Reset() {
	*x = BlackListCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_black_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlackListCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListCreate) ProtoMessage() {}

func (x *BlackListCreate) ProtoReflect() protoreflect.Message {
	mi := &file_black_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListCreate.ProtoReflect.Descriptor instead.
func (*BlackListCreate) Descriptor() ([]byte, []int) {
	return file_black_list_proto_rawDescGZIP(), []int{0}
}

func (x *BlackListCreate) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *BlackListCreate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlackListCreate) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

type BlackListBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployeeId string `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Reason     string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *BlackListBody) Reset() {
	*x = BlackListBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_black_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlackListBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListBody) ProtoMessage() {}

func (x *BlackListBody) ProtoReflect() protoreflect.Message {
	mi := &file_black_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListBody.ProtoReflect.Descriptor instead.
func (*BlackListBody) Descriptor() ([]byte, []int) {
	return file_black_list_proto_rawDescGZIP(), []int{1}
}

func (x *BlackListBody) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *BlackListBody) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BlackListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullName      string `protobuf:"bytes,1,opt,name=FullName,proto3" json:"FullName,omitempty"`
	DateOfBirth   string `protobuf:"bytes,2,opt,name=DateOfBirth,proto3" json:"DateOfBirth,omitempty"`
	Position      string `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	BlacklistedAt string `protobuf:"bytes,5,opt,name=blacklisted_at,json=blacklistedAt,proto3" json:"blacklisted_at,omitempty"`
}

func (x *BlackListRes) Reset() {
	*x = BlackListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_black_list_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlackListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListRes) ProtoMessage() {}

func (x *BlackListRes) ProtoReflect() protoreflect.Message {
	mi := &file_black_list_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListRes.ProtoReflect.Descriptor instead.
func (*BlackListRes) Descriptor() ([]byte, []int) {
	return file_black_list_proto_rawDescGZIP(), []int{2}
}

func (x *BlackListRes) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *BlackListRes) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *BlackListRes) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *BlackListRes) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlackListRes) GetBlacklistedAt() string {
	if x != nil {
		return x.BlacklistedAt
	}
	return ""
}

type GetAllBlackListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlackLists []*BlackListRes `protobuf:"bytes,1,rep,name=black_lists,json=blackLists,proto3" json:"black_lists,omitempty"`
	Count      int32           `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetAllBlackListRes) Reset() {
	*x = GetAllBlackListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_black_list_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBlackListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBlackListRes) ProtoMessage() {}

func (x *GetAllBlackListRes) ProtoReflect() protoreflect.Message {
	mi := &file_black_list_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBlackListRes.ProtoReflect.Descriptor instead.
func (*GetAllBlackListRes) Descriptor() ([]byte, []int) {
	return file_black_list_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllBlackListRes) GetBlackLists() []*BlackListRes {
	if x != nil {
		return x.BlackLists
	}
	return nil
}

func (x *GetAllBlackListRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RemoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployeeId string `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	AddedBy    string `protobuf:"bytes,2,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
}

func (x *RemoveReq) Reset() {
	*x = RemoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_black_list_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReq) ProtoMessage() {}

func (x *RemoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_black_list_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReq.ProtoReflect.Descriptor instead.
func (*RemoveReq) Descriptor() ([]byte, []int) {
	return file_black_list_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveReq) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *RemoveReq) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

var File_black_list_proto protoreflect.FileDescriptor

var file_black_list_proto_rawDesc = []byte{
	0x0a, 0x10, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x0c,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x0f,
	0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x65,
	0x64, 0x5f, 0x62, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x65,
	0x64, 0x42, 0x79, 0x22, 0x48, 0x0a, 0x0d, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x6f, 0x64, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xa7, 0x01,
	0x0a, 0x0c, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x46, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x46, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x61,
	0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x44, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x12, 0x25, 0x0a, 0x0e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x65, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x39, 0x0a,
	0x0b, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x52, 0x0a, 0x62, 0x6c,
	0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x47,
	0x0a, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x65,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x64, 0x64, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x65, 0x64, 0x42, 0x79, 0x32, 0xbf, 0x01, 0x0a, 0x10, 0x42, 0x6c, 0x61, 0x63,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x03,
	0x41, 0x64, 0x64, 0x12, 0x1b, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x1a, 0x10, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x56, 0x6f,
	0x69, 0x64, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x12,
	0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x1a, 0x1e, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x15,
	0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_black_list_proto_rawDescOnce sync.Once
	file_black_list_proto_rawDescData = file_black_list_proto_rawDesc
)

func file_black_list_proto_rawDescGZIP() []byte {
	file_black_list_proto_rawDescOnce.Do(func() {
		file_black_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_black_list_proto_rawDescData)
	})
	return file_black_list_proto_rawDescData
}

var file_black_list_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_black_list_proto_goTypes = []any{
	(*BlackListCreate)(nil),    // 0: black_list.BlackListCreate
	(*BlackListBody)(nil),      // 1: black_list.BlackListBody
	(*BlackListRes)(nil),       // 2: black_list.BlackListRes
	(*GetAllBlackListRes)(nil), // 3: black_list.GetAllBlackListRes
	(*RemoveReq)(nil),          // 4: black_list.RemoveReq
	(*Filter)(nil),             // 5: black_list.Filter
	(*Void)(nil),               // 6: black_list.Void
}
var file_black_list_proto_depIdxs = []int32{
	2, // 0: black_list.GetAllBlackListRes.black_lists:type_name -> black_list.BlackListRes
	0, // 1: black_list.BlackListService.Add:input_type -> black_list.BlackListCreate
	5, // 2: black_list.BlackListService.GetAll:input_type -> black_list.Filter
	4, // 3: black_list.BlackListService.Remove:input_type -> black_list.RemoveReq
	6, // 4: black_list.BlackListService.Add:output_type -> black_list.Void
	3, // 5: black_list.BlackListService.GetAll:output_type -> black_list.GetAllBlackListRes
	6, // 6: black_list.BlackListService.Remove:output_type -> black_list.Void
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_black_list_proto_init() }
func file_black_list_proto_init() {
	if File_black_list_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_black_list_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BlackListCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_black_list_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BlackListBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_black_list_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BlackListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_black_list_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllBlackListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_black_list_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_black_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_black_list_proto_goTypes,
		DependencyIndexes: file_black_list_proto_depIdxs,
		MessageInfos:      file_black_list_proto_msgTypes,
	}.Build()
	File_black_list_proto = out.File
	file_black_list_proto_rawDesc = nil
	file_black_list_proto_goTypes = nil
	file_black_list_proto_depIdxs = nil
}
